// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewQuestChecker creates a new instance of QuestChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestChecker {
	mock := &QuestChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuestChecker is an autogenerated mock type for the QuestChecker type
type QuestChecker struct {
	mock.Mock
}

type QuestChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *QuestChecker) EXPECT() *QuestChecker_Expecter {
	return &QuestChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type QuestChecker
func (_mock *QuestChecker) Check(ctx context.Context, quest model.Quest, data json.RawMessage, seed int64) model.QuestResult {
	ret := _mock.Called(ctx, quest, data, seed)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 model.QuestResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Quest, json.RawMessage, int64) model.QuestResult); ok {
		r0 = returnFunc(ctx, quest, data, seed)
	} else {
		r0 = ret.Get(0).(model.QuestResult)
	}
	return r0
}

// QuestChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type QuestChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - quest model.Quest
//   - data json.RawMessage
//   - seed int64
func (_e *QuestChecker_Expecter) Check(ctx interface{}, quest interface{}, data interface{}, seed interface{}) *QuestChecker_Check_Call {
	return &QuestChecker_Check_Call{Call: _e.mock.On("Check", ctx, quest, data, seed)}
}

func (_c *QuestChecker_Check_Call) Run(run func(ctx context.Context, quest model.Quest, data json.RawMessage, seed int64)) *QuestChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Quest
		if args[1] != nil {
			arg1 = args[1].(model.Quest)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *QuestChecker_Check_Call) Return(questResult model.QuestResult) *QuestChecker_Check_Call {
	_c.Call.Return(questResult)
	return _c
}

func (_c *QuestChecker_Check_Call) RunAndReturn(run func(ctx context.Context, quest model.Quest, data json.RawMessage, seed int64) model.QuestResult) *QuestChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}
