// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewQuestRepository creates a new instance of QuestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestRepository {
	mock := &QuestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuestRepository is an autogenerated mock type for the QuestRepository type
type QuestRepository struct {
	mock.Mock
}

type QuestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *QuestRepository) EXPECT() *QuestRepository_Expecter {
	return &QuestRepository_Expecter{mock: &_m.Mock}
}

// CreateAttempt provides a mock function for the type QuestRepository
func (_mock *QuestRepository) CreateAttempt(ctx context.Context, attempt model.Attempt) (model.Attempt, error) {
	ret := _mock.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttempt")
	}

	var r0 model.Attempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Attempt) (model.Attempt, error)); ok {
		return returnFunc(ctx, attempt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Attempt) model.Attempt); ok {
		r0 = returnFunc(ctx, attempt)
	} else {
		r0 = ret.Get(0).(model.Attempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Attempt) error); ok {
		r1 = returnFunc(ctx, attempt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuestRepository_CreateAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttempt'
type QuestRepository_CreateAttempt_Call struct {
	*mock.Call
}

// CreateAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt model.Attempt
func (_e *QuestRepository_Expecter) CreateAttempt(ctx interface{}, attempt interface{}) *QuestRepository_CreateAttempt_Call {
	return &QuestRepository_CreateAttempt_Call{Call: _e.mock.On("CreateAttempt", ctx, attempt)}
}

func (_c *QuestRepository_CreateAttempt_Call) Run(run func(ctx context.Context, attempt model.Attempt)) *QuestRepository_CreateAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Attempt
		if args[1] != nil {
			arg1 = args[1].(model.Attempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuestRepository_CreateAttempt_Call) Return(attempt1 model.Attempt, err error) *QuestRepository_CreateAttempt_Call {
	_c.Call.Return(attempt1, err)
	return _c
}

func (_c *QuestRepository_CreateAttempt_Call) RunAndReturn(run func(ctx context.Context, attempt model.Attempt) (model.Attempt, error)) *QuestRepository_CreateAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttemptForOwner provides a mock function for the type QuestRepository
func (_mock *QuestRepository) GetAttemptForOwner(ctx context.Context, attemptID string, userID string) (model.Attempt, error) {
	ret := _mock.Called(ctx, attemptID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttemptForOwner")
	}

	var r0 model.Attempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Attempt, error)); ok {
		return returnFunc(ctx, attemptID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Attempt); ok {
		r0 = returnFunc(ctx, attemptID, userID)
	} else {
		r0 = ret.Get(0).(model.Attempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, attemptID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuestRepository_GetAttemptForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttemptForOwner'
type QuestRepository_GetAttemptForOwner_Call struct {
	*mock.Call
}

// GetAttemptForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
//   - userID string
func (_e *QuestRepository_Expecter) GetAttemptForOwner(ctx interface{}, attemptID interface{}, userID interface{}) *QuestRepository_GetAttemptForOwner_Call {
	return &QuestRepository_GetAttemptForOwner_Call{Call: _e.mock.On("GetAttemptForOwner", ctx, attemptID, userID)}
}

func (_c *QuestRepository_GetAttemptForOwner_Call) Run(run func(ctx context.Context, attemptID string, userID string)) *QuestRepository_GetAttemptForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QuestRepository_GetAttemptForOwner_Call) Return(attempt model.Attempt, err error) *QuestRepository_GetAttemptForOwner_Call {
	_c.Call.Return(attempt, err)
	return _c
}

func (_c *QuestRepository_GetAttemptForOwner_Call) RunAndReturn(run func(ctx context.Context, attemptID string, userID string) (model.Attempt, error)) *QuestRepository_GetAttemptForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCheckResult provides a mock function for the type QuestRepository
func (_mock *QuestRepository) InsertCheckResult(ctx context.Context, id string, attemptID string, userID string, result model.QuestResult) error {
	ret := _mock.Called(ctx, id, attemptID, userID, result)

	if len(ret) == 0 {
		panic("no return value specified for InsertCheckResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, model.QuestResult) error); ok {
		r0 = returnFunc(ctx, id, attemptID, userID, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuestRepository_InsertCheckResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCheckResult'
type QuestRepository_InsertCheckResult_Call struct {
	*mock.Call
}

// InsertCheckResult is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - attemptID string
//   - userID string
//   - result model.QuestResult
func (_e *QuestRepository_Expecter) InsertCheckResult(ctx interface{}, id interface{}, attemptID interface{}, userID interface{}, result interface{}) *QuestRepository_InsertCheckResult_Call {
	return &QuestRepository_InsertCheckResult_Call{Call: _e.mock.On("InsertCheckResult", ctx, id, attemptID, userID, result)}
}

func (_c *QuestRepository_InsertCheckResult_Call) Run(run func(ctx context.Context, id string, attemptID string, userID string, result model.QuestResult)) *QuestRepository_InsertCheckResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 model.QuestResult
		if args[4] != nil {
			arg4 = args[4].(model.QuestResult)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *QuestRepository_InsertCheckResult_Call) Return(err error) *QuestRepository_InsertCheckResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuestRepository_InsertCheckResult_Call) RunAndReturn(run func(ctx context.Context, id string, attemptID string, userID string, result model.QuestResult) error) *QuestRepository_InsertCheckResult_Call {
	_c.Call.Return(run)
	return _c
}

// LatestAttemptStatuses provides a mock function for the type QuestRepository
func (_mock *QuestRepository) LatestAttemptStatuses(ctx context.Context, userID string) (map[string]model.AttemptStatus, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LatestAttemptStatuses")
	}

	var r0 map[string]model.AttemptStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]model.AttemptStatus, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]model.AttemptStatus); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]model.AttemptStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuestRepository_LatestAttemptStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestAttemptStatuses'
type QuestRepository_LatestAttemptStatuses_Call struct {
	*mock.Call
}

// LatestAttemptStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *QuestRepository_Expecter) LatestAttemptStatuses(ctx interface{}, userID interface{}) *QuestRepository_LatestAttemptStatuses_Call {
	return &QuestRepository_LatestAttemptStatuses_Call{Call: _e.mock.On("LatestAttemptStatuses", ctx, userID)}
}

func (_c *QuestRepository_LatestAttemptStatuses_Call) Run(run func(ctx context.Context, userID string)) *QuestRepository_LatestAttemptStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuestRepository_LatestAttemptStatuses_Call) Return(stringToAttemptStatus map[string]model.AttemptStatus, err error) *QuestRepository_LatestAttemptStatuses_Call {
	_c.Call.Return(stringToAttemptStatus, err)
	return _c
}

func (_c *QuestRepository_LatestAttemptStatuses_Call) RunAndReturn(run func(ctx context.Context, userID string) (map[string]model.AttemptStatus, error)) *QuestRepository_LatestAttemptStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAttempt provides a mock function for the type QuestRepository
func (_mock *QuestRepository) ResetAttempt(ctx context.Context, attemptID string, userID string) (model.Attempt, error) {
	ret := _mock.Called(ctx, attemptID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetAttempt")
	}

	var r0 model.Attempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Attempt, error)); ok {
		return returnFunc(ctx, attemptID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Attempt); ok {
		r0 = returnFunc(ctx, attemptID, userID)
	} else {
		r0 = ret.Get(0).(model.Attempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, attemptID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuestRepository_ResetAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAttempt'
type QuestRepository_ResetAttempt_Call struct {
	*mock.Call
}

// ResetAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
//   - userID string
func (_e *QuestRepository_Expecter) ResetAttempt(ctx interface{}, attemptID interface{}, userID interface{}) *QuestRepository_ResetAttempt_Call {
	return &QuestRepository_ResetAttempt_Call{Call: _e.mock.On("ResetAttempt", ctx, attemptID, userID)}
}

func (_c *QuestRepository_ResetAttempt_Call) Run(run func(ctx context.Context, attemptID string, userID string)) *QuestRepository_ResetAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QuestRepository_ResetAttempt_Call) Return(attempt model.Attempt, err error) *QuestRepository_ResetAttempt_Call {
	_c.Call.Return(attempt, err)
	return _c
}

func (_c *QuestRepository_ResetAttempt_Call) RunAndReturn(run func(ctx context.Context, attemptID string, userID string) (model.Attempt, error)) *QuestRepository_ResetAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttemptAfterCheck provides a mock function for the type QuestRepository
func (_mock *QuestRepository) UpdateAttemptAfterCheck(ctx context.Context, attemptID string, userID string, status model.AttemptStatus, result model.QuestResult, completedAt *time.Time) (model.Attempt, error) {
	ret := _mock.Called(ctx, attemptID, userID, status, result, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttemptAfterCheck")
	}

	var r0 model.Attempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.AttemptStatus, model.QuestResult, *time.Time) (model.Attempt, error)); ok {
		return returnFunc(ctx, attemptID, userID, status, result, completedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.AttemptStatus, model.QuestResult, *time.Time) model.Attempt); ok {
		r0 = returnFunc(ctx, attemptID, userID, status, result, completedAt)
	} else {
		r0 = ret.Get(0).(model.Attempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, model.AttemptStatus, model.QuestResult, *time.Time) error); ok {
		r1 = returnFunc(ctx, attemptID, userID, status, result, completedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuestRepository_UpdateAttemptAfterCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttemptAfterCheck'
type QuestRepository_UpdateAttemptAfterCheck_Call struct {
	*mock.Call
}

// UpdateAttemptAfterCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
//   - userID string
//   - status model.AttemptStatus
//   - result model.QuestResult
//   - completedAt *time.Time
func (_e *QuestRepository_Expecter) UpdateAttemptAfterCheck(ctx interface{}, attemptID interface{}, userID interface{}, status interface{}, result interface{}, completedAt interface{}) *QuestRepository_UpdateAttemptAfterCheck_Call {
	return &QuestRepository_UpdateAttemptAfterCheck_Call{Call: _e.mock.On("UpdateAttemptAfterCheck", ctx, attemptID, userID, status, result, completedAt)}
}

func (_c *QuestRepository_UpdateAttemptAfterCheck_Call) Run(run func(ctx context.Context, attemptID string, userID string, status model.AttemptStatus, result model.QuestResult, completedAt *time.Time)) *QuestRepository_UpdateAttemptAfterCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.AttemptStatus
		if args[3] != nil {
			arg3 = args[3].(model.AttemptStatus)
		}
		var arg4 model.QuestResult
		if args[4] != nil {
			arg4 = args[4].(model.QuestResult)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *QuestRepository_UpdateAttemptAfterCheck_Call) Return(attempt model.Attempt, err error) *QuestRepository_UpdateAttemptAfterCheck_Call {
	_c.Call.Return(attempt, err)
	return _c
}

func (_c *QuestRepository_UpdateAttemptAfterCheck_Call) RunAndReturn(run func(ctx context.Context, attemptID string, userID string, status model.AttemptStatus, result model.QuestResult, completedAt *time.Time) (model.Attempt, error)) *QuestRepository_UpdateAttemptAfterCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRevealedHintsCount provides a mock function for the type QuestRepository
func (_mock *QuestRepository) UpdateRevealedHintsCount(ctx context.Context, attemptID string, userID string, count int) (model.Attempt, error) {
	ret := _mock.Called(ctx, attemptID, userID, count)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRevealedHintsCount")
	}

	var r0 model.Attempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) (model.Attempt, error)); ok {
		return returnFunc(ctx, attemptID, userID, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) model.Attempt); ok {
		r0 = returnFunc(ctx, attemptID, userID, count)
	} else {
		r0 = ret.Get(0).(model.Attempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, attemptID, userID, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QuestRepository_UpdateRevealedHintsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRevealedHintsCount'
type QuestRepository_UpdateRevealedHintsCount_Call struct {
	*mock.Call
}

// UpdateRevealedHintsCount is a helper method to define mock.On call
//   - ctx context.Context
//   - attemptID string
//   - userID string
//   - count int
func (_e *QuestRepository_Expecter) UpdateRevealedHintsCount(ctx interface{}, attemptID interface{}, userID interface{}, count interface{}) *QuestRepository_UpdateRevealedHintsCount_Call {
	return &QuestRepository_UpdateRevealedHintsCount_Call{Call: _e.mock.On("UpdateRevealedHintsCount", ctx, attemptID, userID, count)}
}

func (_c *QuestRepository_UpdateRevealedHintsCount_Call) Run(run func(ctx context.Context, attemptID string, userID string, count int)) *QuestRepository_UpdateRevealedHintsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *QuestRepository_UpdateRevealedHintsCount_Call) Return(attempt model.Attempt, err error) *QuestRepository_UpdateRevealedHintsCount_Call {
	_c.Call.Return(attempt, err)
	return _c
}

func (_c *QuestRepository_UpdateRevealedHintsCount_Call) RunAndReturn(run func(ctx context.Context, attemptID string, userID string, count int) (model.Attempt, error)) *QuestRepository_UpdateRevealedHintsCount_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertQuests provides a mock function for the type QuestRepository
func (_mock *QuestRepository) UpsertQuests(ctx context.Context, quests []model.Quest) error {
	ret := _mock.Called(ctx, quests)

	if len(ret) == 0 {
		panic("no return value specified for UpsertQuests")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Quest) error); ok {
		r0 = returnFunc(ctx, quests)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuestRepository_UpsertQuests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertQuests'
type QuestRepository_UpsertQuests_Call struct {
	*mock.Call
}

// UpsertQuests is a helper method to define mock.On call
//   - ctx context.Context
//   - quests []model.Quest
func (_e *QuestRepository_Expecter) UpsertQuests(ctx interface{}, quests interface{}) *QuestRepository_UpsertQuests_Call {
	return &QuestRepository_UpsertQuests_Call{Call: _e.mock.On("UpsertQuests", ctx, quests)}
}

func (_c *QuestRepository_UpsertQuests_Call) Run(run func(ctx context.Context, quests []model.Quest)) *QuestRepository_UpsertQuests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Quest
		if args[1] != nil {
			arg1 = args[1].([]model.Quest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QuestRepository_UpsertQuests_Call) Return(err error) *QuestRepository_UpsertQuests_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuestRepository_UpsertQuests_Call) RunAndReturn(run func(ctx context.Context, quests []model.Quest) error) *QuestRepository_UpsertQuests_Call {
	_c.Call.Return(run)
	return _c
}
