// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	"github.com/netquest/netquest/backend/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Demo provides a mock function for the type AuthService
func (_mock *AuthService) Demo(ctx context.Context, client input.ClientInfo) (model.AuthTokens, error) {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Demo")
	}

	var r0 model.AuthTokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ClientInfo) (model.AuthTokens, error)); ok {
		return returnFunc(ctx, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ClientInfo) model.AuthTokens); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Get(0).(model.AuthTokens)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.ClientInfo) error); ok {
		r1 = returnFunc(ctx, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Demo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Demo'
type AuthService_Demo_Call struct {
	*mock.Call
}

// Demo is a helper method to define mock.On call
//   - ctx context.Context
//   - client input.ClientInfo
func (_e *AuthService_Expecter) Demo(ctx interface{}, client interface{}) *AuthService_Demo_Call {
	return &AuthService_Demo_Call{Call: _e.mock.On("Demo", ctx, client)}
}

func (_c *AuthService_Demo_Call) Run(run func(ctx context.Context, client input.ClientInfo)) *AuthService_Demo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.ClientInfo
		if args[1] != nil {
			arg1 = args[1].(input.ClientInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Demo_Call) Return(authTokens model.AuthTokens, err error) *AuthService_Demo_Call {
	_c.Call.Return(authTokens, err)
	return _c
}

func (_c *AuthService_Demo_Call) RunAndReturn(run func(ctx context.Context, client input.ClientInfo) (model.AuthTokens, error)) *AuthService_Demo_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthService
func (_mock *AuthService) Login(ctx context.Context, in input.LoginInput, client input.ClientInfo) (model.AuthTokens, error) {
	ret := _mock.Called(ctx, in, client)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 model.AuthTokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.LoginInput, input.ClientInfo) (model.AuthTokens, error)); ok {
		return returnFunc(ctx, in, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.LoginInput, input.ClientInfo) model.AuthTokens); ok {
		r0 = returnFunc(ctx, in, client)
	} else {
		r0 = ret.Get(0).(model.AuthTokens)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.LoginInput, input.ClientInfo) error); ok {
		r1 = returnFunc(ctx, in, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.LoginInput
//   - client input.ClientInfo
func (_e *AuthService_Expecter) Login(ctx interface{}, in interface{}, client interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, in, client)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, in input.LoginInput, client input.ClientInfo)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.LoginInput
		if args[1] != nil {
			arg1 = args[1].(input.LoginInput)
		}
		var arg2 input.ClientInfo
		if args[2] != nil {
			arg2 = args[2].(input.ClientInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(authTokens model.AuthTokens, err error) *AuthService_Login_Call {
	_c.Call.Return(authTokens, err)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(ctx context.Context, in input.LoginInput, client input.ClientInfo) (model.AuthTokens, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthService
func (_mock *AuthService) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(err error) *AuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function for the type AuthService
func (_mock *AuthService) Me(ctx context.Context, userID string) (model.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type AuthService_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AuthService_Expecter) Me(ctx interface{}, userID interface{}) *AuthService_Me_Call {
	return &AuthService_Me_Call{Call: _e.mock.On("Me", ctx, userID)}
}

func (_c *AuthService_Me_Call) Run(run func(ctx context.Context, userID string)) *AuthService_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Me_Call) Return(user model.User, err error) *AuthService_Me_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthService_Me_Call) RunAndReturn(run func(ctx context.Context, userID string) (model.User, error)) *AuthService_Me_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type AuthService
func (_mock *AuthService) Refresh(ctx context.Context, refreshToken string, client input.ClientInfo) (model.AuthTokens, error) {
	ret := _mock.Called(ctx, refreshToken, client)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 model.AuthTokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, input.ClientInfo) (model.AuthTokens, error)); ok {
		return returnFunc(ctx, refreshToken, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, input.ClientInfo) model.AuthTokens); ok {
		r0 = returnFunc(ctx, refreshToken, client)
	} else {
		r0 = ret.Get(0).(model.AuthTokens)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, input.ClientInfo) error); ok {
		r1 = returnFunc(ctx, refreshToken, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - client input.ClientInfo
func (_e *AuthService_Expecter) Refresh(ctx interface{}, refreshToken interface{}, client interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken, client)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, refreshToken string, client input.ClientInfo)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 input.ClientInfo
		if args[2] != nil {
			arg2 = args[2].(input.ClientInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(authTokens model.AuthTokens, err error) *AuthService_Refresh_Call {
	_c.Call.Return(authTokens, err)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(ctx context.Context, refreshToken string, client input.ClientInfo) (model.AuthTokens, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthService
func (_mock *AuthService) Register(ctx context.Context, in input.RegisterInput, client input.ClientInfo) (model.AuthTokens, error) {
	ret := _mock.Called(ctx, in, client)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 model.AuthTokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.RegisterInput, input.ClientInfo) (model.AuthTokens, error)); ok {
		return returnFunc(ctx, in, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.RegisterInput, input.ClientInfo) model.AuthTokens); ok {
		r0 = returnFunc(ctx, in, client)
	} else {
		r0 = ret.Get(0).(model.AuthTokens)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.RegisterInput, input.ClientInfo) error); ok {
		r1 = returnFunc(ctx, in, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.RegisterInput
//   - client input.ClientInfo
func (_e *AuthService_Expecter) Register(ctx interface{}, in interface{}, client interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, in, client)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, in input.RegisterInput, client input.ClientInfo)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(input.RegisterInput)
		}
		var arg2 input.ClientInfo
		if args[2] != nil {
			arg2 = args[2].(input.ClientInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(authTokens model.AuthTokens, err error) *AuthService_Register_Call {
	_c.Call.Return(authTokens, err)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(ctx context.Context, in input.RegisterInput, client input.ClientInfo) (model.AuthTokens, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
