// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTopologyRepository creates a new instance of TopologyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopologyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopologyRepository {
	mock := &TopologyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TopologyRepository is an autogenerated mock type for the TopologyRepository type
type TopologyRepository struct {
	mock.Mock
}

type TopologyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TopologyRepository) EXPECT() *TopologyRepository_Expecter {
	return &TopologyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TopologyRepository
func (_mock *TopologyRepository) Create(ctx context.Context, topology model.Topology) (model.Topology, error) {
	ret := _mock.Called(ctx, topology)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Topology
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Topology) (model.Topology, error)); ok {
		return returnFunc(ctx, topology)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Topology) model.Topology); ok {
		r0 = returnFunc(ctx, topology)
	} else {
		r0 = ret.Get(0).(model.Topology)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Topology) error); ok {
		r1 = returnFunc(ctx, topology)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TopologyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TopologyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - topology model.Topology
func (_e *TopologyRepository_Expecter) Create(ctx interface{}, topology interface{}) *TopologyRepository_Create_Call {
	return &TopologyRepository_Create_Call{Call: _e.mock.On("Create", ctx, topology)}
}

func (_c *TopologyRepository_Create_Call) Run(run func(ctx context.Context, topology model.Topology)) *TopologyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Topology
		if args[1] != nil {
			arg1 = args[1].(model.Topology)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TopologyRepository_Create_Call) Return(topology1 model.Topology, err error) *TopologyRepository_Create_Call {
	_c.Call.Return(topology1, err)
	return _c
}

func (_c *TopologyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, topology model.Topology) (model.Topology, error)) *TopologyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetForOwner provides a mock function for the type TopologyRepository
func (_mock *TopologyRepository) GetForOwner(ctx context.Context, topologyID string, ownerID string) (model.Topology, error) {
	ret := _mock.Called(ctx, topologyID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetForOwner")
	}

	var r0 model.Topology
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Topology, error)); ok {
		return returnFunc(ctx, topologyID, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Topology); ok {
		r0 = returnFunc(ctx, topologyID, ownerID)
	} else {
		r0 = ret.Get(0).(model.Topology)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, topologyID, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TopologyRepository_GetForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForOwner'
type TopologyRepository_GetForOwner_Call struct {
	*mock.Call
}

// GetForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - topologyID string
//   - ownerID string
func (_e *TopologyRepository_Expecter) GetForOwner(ctx interface{}, topologyID interface{}, ownerID interface{}) *TopologyRepository_GetForOwner_Call {
	return &TopologyRepository_GetForOwner_Call{Call: _e.mock.On("GetForOwner", ctx, topologyID, ownerID)}
}

func (_c *TopologyRepository_GetForOwner_Call) Run(run func(ctx context.Context, topologyID string, ownerID string)) *TopologyRepository_GetForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TopologyRepository_GetForOwner_Call) Return(topology model.Topology, err error) *TopologyRepository_GetForOwner_Call {
	_c.Call.Return(topology, err)
	return _c
}

func (_c *TopologyRepository_GetForOwner_Call) RunAndReturn(run func(ctx context.Context, topologyID string, ownerID string) (model.Topology, error)) *TopologyRepository_GetForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// ListForProjectOwner provides a mock function for the type TopologyRepository
func (_mock *TopologyRepository) ListForProjectOwner(ctx context.Context, projectID string, ownerID string) ([]model.Topology, error) {
	ret := _mock.Called(ctx, projectID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListForProjectOwner")
	}

	var r0 []model.Topology
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Topology, error)); ok {
		return returnFunc(ctx, projectID, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.Topology); ok {
		r0 = returnFunc(ctx, projectID, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Topology)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TopologyRepository_ListForProjectOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForProjectOwner'
type TopologyRepository_ListForProjectOwner_Call struct {
	*mock.Call
}

// ListForProjectOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - ownerID string
func (_e *TopologyRepository_Expecter) ListForProjectOwner(ctx interface{}, projectID interface{}, ownerID interface{}) *TopologyRepository_ListForProjectOwner_Call {
	return &TopologyRepository_ListForProjectOwner_Call{Call: _e.mock.On("ListForProjectOwner", ctx, projectID, ownerID)}
}

func (_c *TopologyRepository_ListForProjectOwner_Call) Run(run func(ctx context.Context, projectID string, ownerID string)) *TopologyRepository_ListForProjectOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TopologyRepository_ListForProjectOwner_Call) Return(topologys []model.Topology, err error) *TopologyRepository_ListForProjectOwner_Call {
	_c.Call.Return(topologys, err)
	return _c
}

func (_c *TopologyRepository_ListForProjectOwner_Call) RunAndReturn(run func(ctx context.Context, projectID string, ownerID string) ([]model.Topology, error)) *TopologyRepository_ListForProjectOwner_Call {
	_c.Call.Return(run)
	return _c
}
