// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewProjectAuthorizer creates a new instance of ProjectAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectAuthorizer {
	mock := &ProjectAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectAuthorizer is an autogenerated mock type for the ProjectAuthorizer type
type ProjectAuthorizer struct {
	mock.Mock
}

type ProjectAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectAuthorizer) EXPECT() *ProjectAuthorizer_Expecter {
	return &ProjectAuthorizer_Expecter{mock: &_m.Mock}
}

// EnsureOwner provides a mock function for the type ProjectAuthorizer
func (_mock *ProjectAuthorizer) EnsureOwner(ctx context.Context, projectID string, ownerID string) error {
	ret := _mock.Called(ctx, projectID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureOwner")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, projectID, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProjectAuthorizer_EnsureOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureOwner'
type ProjectAuthorizer_EnsureOwner_Call struct {
	*mock.Call
}

// EnsureOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - ownerID string
func (_e *ProjectAuthorizer_Expecter) EnsureOwner(ctx interface{}, projectID interface{}, ownerID interface{}) *ProjectAuthorizer_EnsureOwner_Call {
	return &ProjectAuthorizer_EnsureOwner_Call{Call: _e.mock.On("EnsureOwner", ctx, projectID, ownerID)}
}

func (_c *ProjectAuthorizer_EnsureOwner_Call) Run(run func(ctx context.Context, projectID string, ownerID string)) *ProjectAuthorizer_EnsureOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProjectAuthorizer_EnsureOwner_Call) Return(err error) *ProjectAuthorizer_EnsureOwner_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProjectAuthorizer_EnsureOwner_Call) RunAndReturn(run func(ctx context.Context, projectID string, ownerID string) error) *ProjectAuthorizer_EnsureOwner_Call {
	_c.Call.Return(run)
	return _c
}
