// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	"github.com/netquest/netquest/backend/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewProjectService creates a new instance of ProjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectService {
	mock := &ProjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectService is an autogenerated mock type for the ProjectService type
type ProjectService struct {
	mock.Mock
}

type ProjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectService) EXPECT() *ProjectService_Expecter {
	return &ProjectService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProjectService
func (_mock *ProjectService) Create(ctx context.Context, ownerID string, in input.CreateProjectInput) (model.Project, error) {
	ret := _mock.Called(ctx, ownerID, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, input.CreateProjectInput) (model.Project, error)); ok {
		return returnFunc(ctx, ownerID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, input.CreateProjectInput) model.Project); ok {
		r0 = returnFunc(ctx, ownerID, in)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, input.CreateProjectInput) error); ok {
		r1 = returnFunc(ctx, ownerID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - in input.CreateProjectInput
func (_e *ProjectService_Expecter) Create(ctx interface{}, ownerID interface{}, in interface{}) *ProjectService_Create_Call {
	return &ProjectService_Create_Call{Call: _e.mock.On("Create", ctx, ownerID, in)}
}

func (_c *ProjectService_Create_Call) Run(run func(ctx context.Context, ownerID string, in input.CreateProjectInput)) *ProjectService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 input.CreateProjectInput
		if args[2] != nil {
			arg2 = args[2].(input.CreateProjectInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProjectService_Create_Call) Return(project model.Project, err error) *ProjectService_Create_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *ProjectService_Create_Call) RunAndReturn(run func(ctx context.Context, ownerID string, in input.CreateProjectInput) (model.Project, error)) *ProjectService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ProjectService
func (_mock *ProjectService) Delete(ctx context.Context, ownerID string, projectID string) error {
	ret := _mock.Called(ctx, ownerID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, ownerID, projectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProjectService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProjectService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - projectID string
func (_e *ProjectService_Expecter) Delete(ctx interface{}, ownerID interface{}, projectID interface{}) *ProjectService_Delete_Call {
	return &ProjectService_Delete_Call{Call: _e.mock.On("Delete", ctx, ownerID, projectID)}
}

func (_c *ProjectService_Delete_Call) Run(run func(ctx context.Context, ownerID string, projectID string)) *ProjectService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProjectService_Delete_Call) Return(err error) *ProjectService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProjectService_Delete_Call) RunAndReturn(run func(ctx context.Context, ownerID string, projectID string) error) *ProjectService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ProjectService
func (_mock *ProjectService) Get(ctx context.Context, ownerID string, projectID string) (model.Project, error) {
	ret := _mock.Called(ctx, ownerID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Project, error)); ok {
		return returnFunc(ctx, ownerID, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Project); ok {
		r0 = returnFunc(ctx, ownerID, projectID)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProjectService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - projectID string
func (_e *ProjectService_Expecter) Get(ctx interface{}, ownerID interface{}, projectID interface{}) *ProjectService_Get_Call {
	return &ProjectService_Get_Call{Call: _e.mock.On("Get", ctx, ownerID, projectID)}
}

func (_c *ProjectService_Get_Call) Run(run func(ctx context.Context, ownerID string, projectID string)) *ProjectService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProjectService_Get_Call) Return(project model.Project, err error) *ProjectService_Get_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *ProjectService_Get_Call) RunAndReturn(run func(ctx context.Context, ownerID string, projectID string) (model.Project, error)) *ProjectService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ProjectService
func (_mock *ProjectService) List(ctx context.Context, ownerID string) ([]model.Project, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Project, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Project); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProjectService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *ProjectService_Expecter) List(ctx interface{}, ownerID interface{}) *ProjectService_List_Call {
	return &ProjectService_List_Call{Call: _e.mock.On("List", ctx, ownerID)}
}

func (_c *ProjectService_List_Call) Run(run func(ctx context.Context, ownerID string)) *ProjectService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectService_List_Call) Return(projects []model.Project, err error) *ProjectService_List_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *ProjectService_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string) ([]model.Project, error)) *ProjectService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProjectService
func (_mock *ProjectService) Update(ctx context.Context, ownerID string, projectID string, in input.UpdateProjectInput) (model.Project, error) {
	ret := _mock.Called(ctx, ownerID, projectID, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, input.UpdateProjectInput) (model.Project, error)); ok {
		return returnFunc(ctx, ownerID, projectID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, input.UpdateProjectInput) model.Project); ok {
		r0 = returnFunc(ctx, ownerID, projectID, in)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, input.UpdateProjectInput) error); ok {
		r1 = returnFunc(ctx, ownerID, projectID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - projectID string
//   - in input.UpdateProjectInput
func (_e *ProjectService_Expecter) Update(ctx interface{}, ownerID interface{}, projectID interface{}, in interface{}) *ProjectService_Update_Call {
	return &ProjectService_Update_Call{Call: _e.mock.On("Update", ctx, ownerID, projectID, in)}
}

func (_c *ProjectService_Update_Call) Run(run func(ctx context.Context, ownerID string, projectID string, in input.UpdateProjectInput)) *ProjectService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 input.UpdateProjectInput
		if args[3] != nil {
			arg3 = args[3].(input.UpdateProjectInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProjectService_Update_Call) Return(project model.Project, err error) *ProjectService_Update_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *ProjectService_Update_Call) RunAndReturn(run func(ctx context.Context, ownerID string, projectID string, in input.UpdateProjectInput) (model.Project, error)) *ProjectService_Update_Call {
	_c.Call.Return(run)
	return _c
}
