// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSimulationRepository creates a new instance of SimulationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimulationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimulationRepository {
	mock := &SimulationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SimulationRepository is an autogenerated mock type for the SimulationRepository type
type SimulationRepository struct {
	mock.Mock
}

type SimulationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SimulationRepository) EXPECT() *SimulationRepository_Expecter {
	return &SimulationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SimulationRepository
func (_mock *SimulationRepository) Create(ctx context.Context, simulation model.Simulation) (model.Simulation, error) {
	ret := _mock.Called(ctx, simulation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Simulation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Simulation) (model.Simulation, error)); ok {
		return returnFunc(ctx, simulation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Simulation) model.Simulation); ok {
		r0 = returnFunc(ctx, simulation)
	} else {
		r0 = ret.Get(0).(model.Simulation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Simulation) error); ok {
		r1 = returnFunc(ctx, simulation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimulationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SimulationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - simulation model.Simulation
func (_e *SimulationRepository_Expecter) Create(ctx interface{}, simulation interface{}) *SimulationRepository_Create_Call {
	return &SimulationRepository_Create_Call{Call: _e.mock.On("Create", ctx, simulation)}
}

func (_c *SimulationRepository_Create_Call) Run(run func(ctx context.Context, simulation model.Simulation)) *SimulationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Simulation
		if args[1] != nil {
			arg1 = args[1].(model.Simulation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SimulationRepository_Create_Call) Return(simulation1 model.Simulation, err error) *SimulationRepository_Create_Call {
	_c.Call.Return(simulation1, err)
	return _c
}

func (_c *SimulationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, simulation model.Simulation) (model.Simulation, error)) *SimulationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetForOwner provides a mock function for the type SimulationRepository
func (_mock *SimulationRepository) GetForOwner(ctx context.Context, simulationID string, ownerID string) (model.Simulation, error) {
	ret := _mock.Called(ctx, simulationID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetForOwner")
	}

	var r0 model.Simulation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Simulation, error)); ok {
		return returnFunc(ctx, simulationID, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Simulation); ok {
		r0 = returnFunc(ctx, simulationID, ownerID)
	} else {
		r0 = ret.Get(0).(model.Simulation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, simulationID, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimulationRepository_GetForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForOwner'
type SimulationRepository_GetForOwner_Call struct {
	*mock.Call
}

// GetForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - simulationID string
//   - ownerID string
func (_e *SimulationRepository_Expecter) GetForOwner(ctx interface{}, simulationID interface{}, ownerID interface{}) *SimulationRepository_GetForOwner_Call {
	return &SimulationRepository_GetForOwner_Call{Call: _e.mock.On("GetForOwner", ctx, simulationID, ownerID)}
}

func (_c *SimulationRepository_GetForOwner_Call) Run(run func(ctx context.Context, simulationID string, ownerID string)) *SimulationRepository_GetForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimulationRepository_GetForOwner_Call) Return(simulation model.Simulation, err error) *SimulationRepository_GetForOwner_Call {
	_c.Call.Return(simulation, err)
	return _c
}

func (_c *SimulationRepository_GetForOwner_Call) RunAndReturn(run func(ctx context.Context, simulationID string, ownerID string) (model.Simulation, error)) *SimulationRepository_GetForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEvents provides a mock function for the type SimulationRepository
func (_mock *SimulationRepository) InsertEvents(ctx context.Context, simulationID string, events []model.Event) error {
	ret := _mock.Called(ctx, simulationID, events)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.Event) error); ok {
		r0 = returnFunc(ctx, simulationID, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SimulationRepository_InsertEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEvents'
type SimulationRepository_InsertEvents_Call struct {
	*mock.Call
}

// InsertEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - simulationID string
//   - events []model.Event
func (_e *SimulationRepository_Expecter) InsertEvents(ctx interface{}, simulationID interface{}, events interface{}) *SimulationRepository_InsertEvents_Call {
	return &SimulationRepository_InsertEvents_Call{Call: _e.mock.On("InsertEvents", ctx, simulationID, events)}
}

func (_c *SimulationRepository_InsertEvents_Call) Run(run func(ctx context.Context, simulationID string, events []model.Event)) *SimulationRepository_InsertEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.Event
		if args[2] != nil {
			arg2 = args[2].([]model.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimulationRepository_InsertEvents_Call) Return(err error) *SimulationRepository_InsertEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SimulationRepository_InsertEvents_Call) RunAndReturn(run func(ctx context.Context, simulationID string, events []model.Event) error) *SimulationRepository_InsertEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListEventsForOwner provides a mock function for the type SimulationRepository
func (_mock *SimulationRepository) ListEventsForOwner(ctx context.Context, simulationID string, ownerID string) ([]model.Event, error) {
	ret := _mock.Called(ctx, simulationID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListEventsForOwner")
	}

	var r0 []model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Event, error)); ok {
		return returnFunc(ctx, simulationID, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.Event); ok {
		r0 = returnFunc(ctx, simulationID, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, simulationID, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimulationRepository_ListEventsForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEventsForOwner'
type SimulationRepository_ListEventsForOwner_Call struct {
	*mock.Call
}

// ListEventsForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - simulationID string
//   - ownerID string
func (_e *SimulationRepository_Expecter) ListEventsForOwner(ctx interface{}, simulationID interface{}, ownerID interface{}) *SimulationRepository_ListEventsForOwner_Call {
	return &SimulationRepository_ListEventsForOwner_Call{Call: _e.mock.On("ListEventsForOwner", ctx, simulationID, ownerID)}
}

func (_c *SimulationRepository_ListEventsForOwner_Call) Run(run func(ctx context.Context, simulationID string, ownerID string)) *SimulationRepository_ListEventsForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimulationRepository_ListEventsForOwner_Call) Return(events []model.Event, err error) *SimulationRepository_ListEventsForOwner_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *SimulationRepository_ListEventsForOwner_Call) RunAndReturn(run func(ctx context.Context, simulationID string, ownerID string) ([]model.Event, error)) *SimulationRepository_ListEventsForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type SimulationRepository
func (_mock *SimulationRepository) UpdateStatus(ctx context.Context, id string, status model.SimulationStatus, errorMessage *string, startedAt *time.Time, finishedAt *time.Time) error {
	ret := _mock.Called(ctx, id, status, errorMessage, startedAt, finishedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.SimulationStatus, *string, *time.Time, *time.Time) error); ok {
		r0 = returnFunc(ctx, id, status, errorMessage, startedAt, finishedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SimulationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type SimulationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status model.SimulationStatus
//   - errorMessage *string
//   - startedAt *time.Time
//   - finishedAt *time.Time
func (_e *SimulationRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, errorMessage interface{}, startedAt interface{}, finishedAt interface{}) *SimulationRepository_UpdateStatus_Call {
	return &SimulationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, errorMessage, startedAt, finishedAt)}
}

func (_c *SimulationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status model.SimulationStatus, errorMessage *string, startedAt *time.Time, finishedAt *time.Time)) *SimulationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.SimulationStatus
		if args[2] != nil {
			arg2 = args[2].(model.SimulationStatus)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *SimulationRepository_UpdateStatus_Call) Return(err error) *SimulationRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SimulationRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status model.SimulationStatus, errorMessage *string, startedAt *time.Time, finishedAt *time.Time) error) *SimulationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
