// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewEventProducer creates a new instance of EventProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventProducer {
	mock := &EventProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventProducer is an autogenerated mock type for the EventProducer type
type EventProducer struct {
	mock.Mock
}

type EventProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *EventProducer) EXPECT() *EventProducer_Expecter {
	return &EventProducer_Expecter{mock: &_m.Mock}
}

// ProduceSimulationEvent provides a mock function for the type EventProducer
func (_mock *EventProducer) ProduceSimulationEvent(ctx context.Context, simulationID string, event model.Event) error {
	ret := _mock.Called(ctx, simulationID, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceSimulationEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Event) error); ok {
		r0 = returnFunc(ctx, simulationID, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventProducer_ProduceSimulationEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceSimulationEvent'
type EventProducer_ProduceSimulationEvent_Call struct {
	*mock.Call
}

// ProduceSimulationEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - simulationID string
//   - event model.Event
func (_e *EventProducer_Expecter) ProduceSimulationEvent(ctx interface{}, simulationID interface{}, event interface{}) *EventProducer_ProduceSimulationEvent_Call {
	return &EventProducer_ProduceSimulationEvent_Call{Call: _e.mock.On("ProduceSimulationEvent", ctx, simulationID, event)}
}

func (_c *EventProducer_ProduceSimulationEvent_Call) Run(run func(ctx context.Context, simulationID string, event model.Event)) *EventProducer_ProduceSimulationEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Event
		if args[2] != nil {
			arg2 = args[2].(model.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventProducer_ProduceSimulationEvent_Call) Return(err error) *EventProducer_ProduceSimulationEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventProducer_ProduceSimulationEvent_Call) RunAndReturn(run func(ctx context.Context, simulationID string, event model.Event) error) *EventProducer_ProduceSimulationEvent_Call {
	_c.Call.Return(run)
	return _c
}
