// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSimulationEngine creates a new instance of SimulationEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimulationEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimulationEngine {
	mock := &SimulationEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SimulationEngine is an autogenerated mock type for the SimulationEngine type
type SimulationEngine struct {
	mock.Mock
}

type SimulationEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *SimulationEngine) EXPECT() *SimulationEngine_Expecter {
	return &SimulationEngine_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type SimulationEngine
func (_mock *SimulationEngine) Run(ctx context.Context, req model.RunRequest) (model.RunResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 model.RunResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.RunRequest) (model.RunResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.RunRequest) model.RunResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(model.RunResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.RunRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimulationEngine_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type SimulationEngine_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.RunRequest
func (_e *SimulationEngine_Expecter) Run(ctx interface{}, req interface{}) *SimulationEngine_Run_Call {
	return &SimulationEngine_Run_Call{Call: _e.mock.On("Run", ctx, req)}
}

func (_c *SimulationEngine_Run_Call) Run(run func(ctx context.Context, req model.RunRequest)) *SimulationEngine_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.RunRequest
		if args[1] != nil {
			arg1 = args[1].(model.RunRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SimulationEngine_Run_Call) Return(runResult model.RunResult, err error) *SimulationEngine_Run_Call {
	_c.Call.Return(runResult, err)
	return _c
}

func (_c *SimulationEngine_Run_Call) RunAndReturn(run func(ctx context.Context, req model.RunRequest) (model.RunResult, error)) *SimulationEngine_Run_Call {
	_c.Call.Return(run)
	return _c
}
