// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTopologyReader creates a new instance of TopologyReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopologyReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopologyReader {
	mock := &TopologyReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TopologyReader is an autogenerated mock type for the TopologyReader type
type TopologyReader struct {
	mock.Mock
}

type TopologyReader_Expecter struct {
	mock *mock.Mock
}

func (_m *TopologyReader) EXPECT() *TopologyReader_Expecter {
	return &TopologyReader_Expecter{mock: &_m.Mock}
}

// GetForOwner provides a mock function for the type TopologyReader
func (_mock *TopologyReader) GetForOwner(ctx context.Context, topologyID string, ownerID string) (model.Topology, error) {
	ret := _mock.Called(ctx, topologyID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetForOwner")
	}

	var r0 model.Topology
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Topology, error)); ok {
		return returnFunc(ctx, topologyID, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Topology); ok {
		r0 = returnFunc(ctx, topologyID, ownerID)
	} else {
		r0 = ret.Get(0).(model.Topology)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, topologyID, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TopologyReader_GetForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForOwner'
type TopologyReader_GetForOwner_Call struct {
	*mock.Call
}

// GetForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - topologyID string
//   - ownerID string
func (_e *TopologyReader_Expecter) GetForOwner(ctx interface{}, topologyID interface{}, ownerID interface{}) *TopologyReader_GetForOwner_Call {
	return &TopologyReader_GetForOwner_Call{Call: _e.mock.On("GetForOwner", ctx, topologyID, ownerID)}
}

func (_c *TopologyReader_GetForOwner_Call) Run(run func(ctx context.Context, topologyID string, ownerID string)) *TopologyReader_GetForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TopologyReader_GetForOwner_Call) Return(topology model.Topology, err error) *TopologyReader_GetForOwner_Call {
	_c.Call.Return(topology, err)
	return _c
}

func (_c *TopologyReader_GetForOwner_Call) RunAndReturn(run func(ctx context.Context, topologyID string, ownerID string) (model.Topology, error)) *TopologyReader_GetForOwner_Call {
	_c.Call.Return(run)
	return _c
}
