// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	"github.com/netquest/netquest/backend/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewSimulationService creates a new instance of SimulationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSimulationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SimulationService {
	mock := &SimulationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SimulationService is an autogenerated mock type for the SimulationService type
type SimulationService struct {
	mock.Mock
}

type SimulationService_Expecter struct {
	mock *mock.Mock
}

func (_m *SimulationService) EXPECT() *SimulationService_Expecter {
	return &SimulationService_Expecter{mock: &_m.Mock}
}

// Events provides a mock function for the type SimulationService
func (_mock *SimulationService) Events(ctx context.Context, userID string, simulationID string) ([]model.Event, error) {
	ret := _mock.Called(ctx, userID, simulationID)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []model.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Event, error)); ok {
		return returnFunc(ctx, userID, simulationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.Event); ok {
		r0 = returnFunc(ctx, userID, simulationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, simulationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimulationService_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type SimulationService_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - simulationID string
func (_e *SimulationService_Expecter) Events(ctx interface{}, userID interface{}, simulationID interface{}) *SimulationService_Events_Call {
	return &SimulationService_Events_Call{Call: _e.mock.On("Events", ctx, userID, simulationID)}
}

func (_c *SimulationService_Events_Call) Run(run func(ctx context.Context, userID string, simulationID string)) *SimulationService_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimulationService_Events_Call) Return(events []model.Event, err error) *SimulationService_Events_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *SimulationService_Events_Call) RunAndReturn(run func(ctx context.Context, userID string, simulationID string) ([]model.Event, error)) *SimulationService_Events_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SimulationService
func (_mock *SimulationService) Get(ctx context.Context, userID string, simulationID string) (model.Simulation, error) {
	ret := _mock.Called(ctx, userID, simulationID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Simulation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Simulation, error)); ok {
		return returnFunc(ctx, userID, simulationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Simulation); ok {
		r0 = returnFunc(ctx, userID, simulationID)
	} else {
		r0 = ret.Get(0).(model.Simulation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, simulationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SimulationService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SimulationService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - simulationID string
func (_e *SimulationService_Expecter) Get(ctx interface{}, userID interface{}, simulationID interface{}) *SimulationService_Get_Call {
	return &SimulationService_Get_Call{Call: _e.mock.On("Get", ctx, userID, simulationID)}
}

func (_c *SimulationService_Get_Call) Run(run func(ctx context.Context, userID string, simulationID string)) *SimulationService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimulationService_Get_Call) Return(simulation model.Simulation, err error) *SimulationService_Get_Call {
	_c.Call.Return(simulation, err)
	return _c
}

func (_c *SimulationService_Get_Call) RunAndReturn(run func(ctx context.Context, userID string, simulationID string) (model.Simulation, error)) *SimulationService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type SimulationService
func (_mock *SimulationService) Start(ctx context.Context, userID string, in input.StartSimulationInput) (model.Simulation, model.RunResult, error) {
	ret := _mock.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 model.Simulation
	var r1 model.RunResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, input.StartSimulationInput) (model.Simulation, model.RunResult, error)); ok {
		return returnFunc(ctx, userID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, input.StartSimulationInput) model.Simulation); ok {
		r0 = returnFunc(ctx, userID, in)
	} else {
		r0 = ret.Get(0).(model.Simulation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, input.StartSimulationInput) model.RunResult); ok {
		r1 = returnFunc(ctx, userID, in)
	} else {
		r1 = ret.Get(1).(model.RunResult)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, input.StartSimulationInput) error); ok {
		r2 = returnFunc(ctx, userID, in)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// SimulationService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type SimulationService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - in input.StartSimulationInput
func (_e *SimulationService_Expecter) Start(ctx interface{}, userID interface{}, in interface{}) *SimulationService_Start_Call {
	return &SimulationService_Start_Call{Call: _e.mock.On("Start", ctx, userID, in)}
}

func (_c *SimulationService_Start_Call) Run(run func(ctx context.Context, userID string, in input.StartSimulationInput)) *SimulationService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 input.StartSimulationInput
		if args[2] != nil {
			arg2 = args[2].(input.StartSimulationInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SimulationService_Start_Call) Return(simulation model.Simulation, runResult model.RunResult, err error) *SimulationService_Start_Call {
	_c.Call.Return(simulation, runResult, err)
	return _c
}

func (_c *SimulationService_Start_Call) RunAndReturn(run func(ctx context.Context, userID string, in input.StartSimulationInput) (model.Simulation, model.RunResult, error)) *SimulationService_Start_Call {
	_c.Call.Return(run)
	return _c
}
