// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAccessTokenParser creates a new instance of AccessTokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessTokenParser {
	mock := &AccessTokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccessTokenParser is an autogenerated mock type for the AccessTokenParser type
type AccessTokenParser struct {
	mock.Mock
}

type AccessTokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *AccessTokenParser) EXPECT() *AccessTokenParser_Expecter {
	return &AccessTokenParser_Expecter{mock: &_m.Mock}
}

// ParseAccessToken provides a mock function for the type AccessTokenParser
func (_mock *AccessTokenParser) ParseAccessToken(raw string) (model.Principal, error) {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 model.Principal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.Principal, error)); ok {
		return returnFunc(raw)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.Principal); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(model.Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccessTokenParser_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type AccessTokenParser_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - raw string
func (_e *AccessTokenParser_Expecter) ParseAccessToken(raw interface{}) *AccessTokenParser_ParseAccessToken_Call {
	return &AccessTokenParser_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", raw)}
}

func (_c *AccessTokenParser_ParseAccessToken_Call) Run(run func(raw string)) *AccessTokenParser_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AccessTokenParser_ParseAccessToken_Call) Return(principal model.Principal, err error) *AccessTokenParser_ParseAccessToken_Call {
	_c.Call.Return(principal, err)
	return _c
}

func (_c *AccessTokenParser_ParseAccessToken_Call) RunAndReturn(run func(raw string) (model.Principal, error)) *AccessTokenParser_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
