// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewAccessTokenIssuer creates a new instance of AccessTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessTokenIssuer {
	mock := &AccessTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccessTokenIssuer is an autogenerated mock type for the AccessTokenIssuer type
type AccessTokenIssuer struct {
	mock.Mock
}

type AccessTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *AccessTokenIssuer) EXPECT() *AccessTokenIssuer_Expecter {
	return &AccessTokenIssuer_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type AccessTokenIssuer
func (_mock *AccessTokenIssuer) GenerateAccessToken(userID string, email string, role string, now time.Time) (string, error) {
	ret := _mock.Called(userID, email, role, now)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, time.Time) (string, error)); ok {
		return returnFunc(userID, email, role, now)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, time.Time) string); ok {
		r0 = returnFunc(userID, email, role, now)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, time.Time) error); ok {
		r1 = returnFunc(userID, email, role, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccessTokenIssuer_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type AccessTokenIssuer_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID string
//   - email string
//   - role string
//   - now time.Time
func (_e *AccessTokenIssuer_Expecter) GenerateAccessToken(userID interface{}, email interface{}, role interface{}, now interface{}) *AccessTokenIssuer_GenerateAccessToken_Call {
	return &AccessTokenIssuer_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, email, role, now)}
}

func (_c *AccessTokenIssuer_GenerateAccessToken_Call) Run(run func(userID string, email string, role string, now time.Time)) *AccessTokenIssuer_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AccessTokenIssuer_GenerateAccessToken_Call) Return(s string, err error) *AccessTokenIssuer_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AccessTokenIssuer_GenerateAccessToken_Call) RunAndReturn(run func(userID string, email string, role string, now time.Time) (string, error)) *AccessTokenIssuer_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
