// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) Create(ctx context.Context, token model.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *RefreshTokenRepository_Create_Call {
	return &RefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *RefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token model.RefreshToken)) *RefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(model.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) Return(err error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token model.RefreshToken) error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByHash provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) FindActiveByHash(ctx context.Context, tokenHash string, now time.Time) (model.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash, now)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByHash")
	}

	var r0 model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (model.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) model.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash, now)
	} else {
		r0 = ret.Get(0).(model.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, tokenHash, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshTokenRepository_FindActiveByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByHash'
type RefreshTokenRepository_FindActiveByHash_Call struct {
	*mock.Call
}

// FindActiveByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - now time.Time
func (_e *RefreshTokenRepository_Expecter) FindActiveByHash(ctx interface{}, tokenHash interface{}, now interface{}) *RefreshTokenRepository_FindActiveByHash_Call {
	return &RefreshTokenRepository_FindActiveByHash_Call{Call: _e.mock.On("FindActiveByHash", ctx, tokenHash, now)}
}

func (_c *RefreshTokenRepository_FindActiveByHash_Call) Run(run func(ctx context.Context, tokenHash string, now time.Time)) *RefreshTokenRepository_FindActiveByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_FindActiveByHash_Call) Return(refreshToken model.RefreshToken, err error) *RefreshTokenRepository_FindActiveByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *RefreshTokenRepository_FindActiveByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, now time.Time) (model.RefreshToken, error)) *RefreshTokenRepository_FindActiveByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByHash provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeByHash(ctx context.Context, tokenHash string, now time.Time) error {
	ret := _mock.Called(ctx, tokenHash, now)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, tokenHash, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_RevokeByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByHash'
type RefreshTokenRepository_RevokeByHash_Call struct {
	*mock.Call
}

// RevokeByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - now time.Time
func (_e *RefreshTokenRepository_Expecter) RevokeByHash(ctx interface{}, tokenHash interface{}, now interface{}) *RefreshTokenRepository_RevokeByHash_Call {
	return &RefreshTokenRepository_RevokeByHash_Call{Call: _e.mock.On("RevokeByHash", ctx, tokenHash, now)}
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) Run(run func(ctx context.Context, tokenHash string, now time.Time)) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) Return(err error) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, now time.Time) error) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(run)
	return _c
}
