// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(ctx context.Context, user model.User) (model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, user interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, user model.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(user1 model.User, err error) *UserRepository_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user model.User) (model.User, error)) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByEmail(ctx context.Context, email string) (model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *UserRepository_FindByEmail_Call {
	return &UserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *UserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByEmail_Call) Return(user model.User, err error) *UserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (model.User, error)) *UserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByID(ctx context.Context, id string) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(user model.User, err error) *UserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertDemoUser provides a mock function for the type UserRepository
func (_mock *UserRepository) UpsertDemoUser(ctx context.Context, user model.User) (model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDemoUser")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_UpsertDemoUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertDemoUser'
type UserRepository_UpsertDemoUser_Call struct {
	*mock.Call
}

// UpsertDemoUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *UserRepository_Expecter) UpsertDemoUser(ctx interface{}, user interface{}) *UserRepository_UpsertDemoUser_Call {
	return &UserRepository_UpsertDemoUser_Call{Call: _e.mock.On("UpsertDemoUser", ctx, user)}
}

func (_c *UserRepository_UpsertDemoUser_Call) Run(run func(ctx context.Context, user model.User)) *UserRepository_UpsertDemoUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_UpsertDemoUser_Call) Return(user1 model.User, err error) *UserRepository_UpsertDemoUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepository_UpsertDemoUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) (model.User, error)) *UserRepository_UpsertDemoUser_Call {
	_c.Call.Return(run)
	return _c
}
