// Code generated for gerega mikhail service
// ©2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/netquest/netquest/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewProjectRepository creates a new instance of ProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectRepository {
	mock := &ProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectRepository is an autogenerated mock type for the ProjectRepository type
type ProjectRepository struct {
	mock.Mock
}

type ProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectRepository) EXPECT() *ProjectRepository_Expecter {
	return &ProjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProjectRepository
func (_mock *ProjectRepository) Create(ctx context.Context, project model.Project) (model.Project, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Project) (model.Project, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Project) model.Project); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project model.Project
func (_e *ProjectRepository_Expecter) Create(ctx interface{}, project interface{}) *ProjectRepository_Create_Call {
	return &ProjectRepository_Create_Call{Call: _e.mock.On("Create", ctx, project)}
}

func (_c *ProjectRepository_Create_Call) Run(run func(ctx context.Context, project model.Project)) *ProjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Project
		if args[1] != nil {
			arg1 = args[1].(model.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectRepository_Create_Call) Return(project1 model.Project, err error) *ProjectRepository_Create_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *ProjectRepository_Create_Call) RunAndReturn(run func(ctx context.Context, project model.Project) (model.Project, error)) *ProjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOwner provides a mock function for the type ProjectRepository
func (_mock *ProjectRepository) GetByOwner(ctx context.Context, ownerID string, projectID string) (model.Project, error) {
	ret := _mock.Called(ctx, ownerID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwner")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Project, error)); ok {
		return returnFunc(ctx, ownerID, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Project); ok {
		r0 = returnFunc(ctx, ownerID, projectID)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectRepository_GetByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOwner'
type ProjectRepository_GetByOwner_Call struct {
	*mock.Call
}

// GetByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - projectID string
func (_e *ProjectRepository_Expecter) GetByOwner(ctx interface{}, ownerID interface{}, projectID interface{}) *ProjectRepository_GetByOwner_Call {
	return &ProjectRepository_GetByOwner_Call{Call: _e.mock.On("GetByOwner", ctx, ownerID, projectID)}
}

func (_c *ProjectRepository_GetByOwner_Call) Run(run func(ctx context.Context, ownerID string, projectID string)) *ProjectRepository_GetByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProjectRepository_GetByOwner_Call) Return(project model.Project, err error) *ProjectRepository_GetByOwner_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *ProjectRepository_GetByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerID string, projectID string) (model.Project, error)) *ProjectRepository_GetByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ProjectRepository
func (_mock *ProjectRepository) List(ctx context.Context, ownerID string) ([]model.Project, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Project, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Project); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *ProjectRepository_Expecter) List(ctx interface{}, ownerID interface{}) *ProjectRepository_List_Call {
	return &ProjectRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID)}
}

func (_c *ProjectRepository_List_Call) Run(run func(ctx context.Context, ownerID string)) *ProjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectRepository_List_Call) Return(projects []model.Project, err error) *ProjectRepository_List_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *ProjectRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string) ([]model.Project, error)) *ProjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type ProjectRepository
func (_mock *ProjectRepository) SoftDelete(ctx context.Context, ownerID string, projectID string) error {
	ret := _mock.Called(ctx, ownerID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, ownerID, projectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProjectRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type ProjectRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - projectID string
func (_e *ProjectRepository_Expecter) SoftDelete(ctx interface{}, ownerID interface{}, projectID interface{}) *ProjectRepository_SoftDelete_Call {
	return &ProjectRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, ownerID, projectID)}
}

func (_c *ProjectRepository_SoftDelete_Call) Run(run func(ctx context.Context, ownerID string, projectID string)) *ProjectRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProjectRepository_SoftDelete_Call) Return(err error) *ProjectRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProjectRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, ownerID string, projectID string) error) *ProjectRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProjectRepository
func (_mock *ProjectRepository) Update(ctx context.Context, project model.Project) (model.Project, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Project) (model.Project, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Project) model.Project); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - project model.Project
func (_e *ProjectRepository_Expecter) Update(ctx interface{}, project interface{}) *ProjectRepository_Update_Call {
	return &ProjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, project)}
}

func (_c *ProjectRepository_Update_Call) Run(run func(ctx context.Context, project model.Project)) *ProjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Project
		if args[1] != nil {
			arg1 = args[1].(model.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectRepository_Update_Call) Return(project1 model.Project, err error) *ProjectRepository_Update_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *ProjectRepository_Update_Call) RunAndReturn(run func(ctx context.Context, project model.Project) (model.Project, error)) *ProjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
